language: node_js
dist: focal
node_js:
  - 18

services:
  - rabbitmq

branches:
  only:
  - master

before_install:
# Configure Git
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"

install:
- yarn

#before_script:
#  - sudo rabbitmqctl stop_app
#  - sudo rabbitmqctl reset
#  - sudo rabbitmqctl start_app
#  - sudo rabbitmq-plugins enable rabbitmq_management
#  - sudo rabbitmq-plugins enable rabbitmq_shovel
#  - sudo rabbitmq-plugins enable rabbitmq_shovel_management
#  - sudo service rabbitmq-server restart

script:
- yarn test

