language: node_js

node_js:
  - "10.4.1"

services:
  - rabbitmq

before_script:
  - sudo rabbitmqctl stop_app
  - sudo rabbitmqctl reset
  - sudo rabbitmqctl start_app
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_shovel
  - sudo rabbitmq-plugins enable rabbitmq_shovel_management
  - sudo service rabbitmq-server restart

script:
  npm run test:all
