language: node_js

node_js:
  - "10.4.1"

services:
  - rabbitmq

branches:
  only:
  - master

before_install:
# Configure Git
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"

# Get all tags of git repo
- git fetch origin 'refs/tags/*:refs/tags/*'

before_script:
  - sudo rabbitmqctl stop_app
  - sudo rabbitmqctl reset
  - sudo rabbitmqctl start_app
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_shovel
  - sudo rabbitmq-plugins enable rabbitmq_shovel_management
  - sudo service rabbitmq-server restart

script:
  npm run test:all

after_success:
# Bump version
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || bin/bump-version
