version: "3.2"

services:
  rabbitmq:
    container_name: rabbitmq
    build: ./docker/rabbitmq
    profiles:
      - rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis
    volumes:
      - relay-redis:/data
    profiles:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  relay:
    container_name: relay
    build: .
    volumes:
      - relay-storage:/storage
    ports:
      - "3000:3000"
    environment:
      - INBOX_STORAGE=/storage
      - RABBITMQ_CLIENT=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379

volumes:
  relay-storage:
  relay-redis:
