version: '3.2'

services:
  relay:
    container_name: relay
    build: .
    volumes:
      - relay-storage:/storage
    ports:
      - '3000:3000'
      - '${WS_PORT:-8080}:8080'
    environment:
      - INBOX_STORAGE=/storage
      - RABBITMQ_CLIENT=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - WS_PORT=${WS_PORT:-8080}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    build: ./docker/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5672:5672'

  redis:
    container_name: redis
    image: redis
    volumes:
      - relay-redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '6379:6379'

volumes:
  relay-storage:
  relay-redis:
